apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: voice-auth
resources:
  - namespace.yaml
  - config.yaml
  - frontend.yaml
  - backend.yaml
  - ml-server.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: voice-auth
