apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: voice-auth/frontend
    newName: ghcr.io/sem5-dse-project/voice-auth-frontend
    newTag: sha-a690da8
  - name: voice-auth/backend
    newName: ghcr.io/sem5-dse-project/voice-auth-backend
    newTag: sha-a690da8
  - name: voice-auth/ml-server
    newName: ghcr.io/sem5-dse-project/voice-auth-ml
    newTag: sha-a690da8
